<?php
class FencingTimeCompetition extends CompetitionCSV
{
	function isValid($html)
	{
		if ( is_object($html) )
		{
			if ( strpos($html->plaintext, "Results generated by Fencing Time tournament software:") )
			{
				return true;
			}
		}
		return false;
	}
	
	function parse($html)
	{
		$this->setName(cleanup($html->find('table.headertable tr', 0)->plaintext));

		$headerOrder = array();
		foreach ($html->find('table.reporttable') as $resultsHtml);
		{
			foreach($resultsHtml->find('tr.tablehead') as $element)
			{
				foreach ($element->find('td') as $thing)
				{
					$headerOrder[] = cleanup($thing->plaintext);
				}
			}
		}

		foreach ($html->find('table.reporttable') as $resultsHtml);
		{
			foreach($resultsHtml->find('tr') as $element)
			{
				if ( $element->class != "tablehead" )
				{
					$result = new ResultCSV();
					$i = 0;
					foreach ($element->find('td') as $thing)
					{
						// For FencingTime, need to split the name
						if ($headerOrder[$i] == "Name")
						{
							list($surname, $forename) = split(", ", $thing->plaintext);
							$result->setSurname(cleanup($surname));
							$result->setForename(cleanup($forename));
						}
						else
						{
							$result->setAttribute($headerOrder[$i], cleanup($thing->plaintext));
						}
						$i++;
					}
					$this->addResult($result);
				}
			}
		}
	}
}

?>